#!/usr/bin/env python3

import sys


def factorize_number(num):
    factors = []
    for i in range(2, num):
        if num % i == 0:
            factors.append((i, num // i))
            break
    return factors


def main(filename):
    with open(filename, 'r') as file:
        for line in file:
            num = int(line)
            factors = factorize_number(num)
            if factors:
                p, q = factors[0]
                print(f"{num}={p}*{q}")


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)
    filename = sys.argv[1]
    main(filename)
