#!/usr/bin/env python3

import sys
import os

def factorize_number(num):
    for i in range(2, num // 2 + 1):
        if num % i == 0:
            return i, num // i
    return None, None

def main(filename):
    with open(filename, 'r') as file:
        for line in file:
            num = int(line.strip())
            p, q = factorize_number(num)
            print(f"{num}={p}*{q}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    filename = sys.argv[1]
    main(filename)
