#!/usr/bin/env python3

import sys


def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True


def factorize_rsa_number(num):
    factors = []
    for i in range(2, num):
        if num % i == 0 and is_prime(i) and is_prime(num // i):
            factors.append((i, num // i))
            break
    return factors


def main(filename):
    with open(filename, 'r') as file:
        for line in file:
            num = int(line)
            factors = factorize_rsa_number(num)
            if factors:
                p, q = factors[0]
                print(f"{num}={p}*{q}")
            else:
                print(f"No prime factors found for {num}")


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: rsa <file>")
        sys.exit(1)
    filename = sys.argv[1]
    main(filename)

